### ISSUE TITLE
[DEBUG_API] [USER] User subscribers and connections

### ISSUE THREAD

**Issue by hgranule** [hgranule/matcha#6]
`POST /debug/user/:id/subscribe`
Subscribe user with `id = ":id"` to user list. User id list is taken from JSON body

`DELETE /debug/user/:id/unsubscribe`
Unsubscribe user with `id = ":id"` from user list. User id list is taken from JSON body

`GET /debug/user/:id/subscribers`
Get all user's subscribers

`GET /debug/user/:id/subscriptions`
Get all user's subscriptions

`GET /debug/user/:id/connections`
Get all user's connections (connection is created when both users are subscribed to each other)

**Comment by hgranule** [comment]
@hgranule make it!!!

**Comment by secondfry** [comment]
What happened to this and previous two issues? Was looking into following project updates.
